#!/bin/sh
cat > /app/.env << EOF
TELEGRAM_API_ID=${TELEGRAM_API_ID}
TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
TELEGRAM_SESSION_STRING=${TELEGRAM_SESSION_STRING}
TELEGRAM_SESSION_NAME=${TELEGRAM_SESSION_NAME}
EOF
exec mcp-proxy --host=0.0.0.0 --port=${PORT:-8080} -- python /app/run_wrapper.py