#!/bin/sh
cat > /app/.env << EOF
TELEGRAM_API_ID=${TELEGRAM_API_ID}
TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
TELEGRAM_SESSION_STRING=${TELEGRAM_SESSION_STRING}
TELEGRAM_SESSION_NAME=${TELEGRAM_SESSION_NAME}
WEBHOOK_URL=${WEBHOOK_URL}
WEBHOOK_API_KEY=${WEBHOOK_API_KEY}
API_ACCESS_TOKEN=${API_ACCESS_TOKEN}
EOF
export MCP_TRANSPORT=sse
export PORT=${PORT:-8080}
exec python /app/main.py
