#!/bin/sh
cat > /app/.env << EOF
TELEGRAM_API_ID=${TELEGRAM_API_ID}
TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
TELEGRAM_SESSION_STRING=${TELEGRAM_SESSION_STRING}
TELEGRAM_SESSION_NAME=${TELEGRAM_SESSION_NAME}
WEBHOOK_URL=${WEBHOOK_URL}
WEBHOOK_API_KEY=${WEBHOOK_API_KEY}
EOF
exec mcp-proxy --host=0.0.0.0 --port=${PORT:-8080} -- python /app/run_wrapper.py